#!/bin/bash

cd $(dirname $0)/..

aws cloudformation deploy \
  --region "ap-southeast-1" \
  --template-file aws/cloudformation/template.yml \
  --stack-name sycLambda  \
  --tags Key1=sycAWSTraining